---
stack:
  repository: https://github.com/gimlet-io/gimlet-stack-reference.git?tag=v0.11.0
config:
  loki:
    enabled: true
  nginx:
    enabled: true
    host: adam.dzsak
  prometheus:
    enabled: true
