apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: deploy-key-dzsak-k8s-stack
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIFkak95G/ONd3W+yC0YOGvM4mLN5lSuOMtqaESGfAgOp
    -----END PRIVATE KEY-----
  identity.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPAT851zLb4EPeSQqLhWokCGukJO/SqRgEAUqPS1JXnT
  known_hosts: |
    github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
