---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-repo-dzsak-k8s-stack
  namespace: flux-system
spec:
  interval: 15s
  ref:
    branch: main
  secretRef:
    name: deploy-key-dzsak-k8s-stack
  url: ssh://git@github.com/dzsak/k8s-stack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-repo-dzsak-k8s-stack
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo-dzsak-k8s-stack
  validation: client
